# This file contains a master definition of all the settings that app expects to be able to run
# Fields left blank are intended to be overwritten by environment specific settings such as dev.yml or local.yml
# TODO: Write a meteor launcher script that takes the yaml config and exports env vars and writes to METEOR_SETTINGS
# It should also take care of overwriting settings with env vars as appropriate
# Consider using something like https://github.com/jsoverson/grunt-env
# To overwrite settings.hardMinBuild, do
#   export settings_hardMinbuild="111"
# To overwrite azure accessKey
#   export settings_azure_accessKey="223232"
# Only string values should be overwrittenn, overwriting non-string values is not expected

env:
  MONGO_URL:
  ROOT_URL:
settings:
  facebook:
    appId:
    secret:
  google:
    clientId: '206738713177-70a56st49c3revvi2m44o9ibkfdnqoig.apps.googleusercontent.com'
    secret: 'TjCos4w3_h_CYByElarS3YxL'
  azure:
    accountId: 'ketch'
    accessKey: 'wRHy5KjIvuNt+Z7WmutSm+Ms1iRHxdnh2ZqgA+2w2MuIInXCDtq2BtE6XbuJlPFggO2BCO6KmOr8PCwYHuIlqA=='
    container:
  apns:
    keyPassphrase: 'GTgQLFnNrPnPY6Qbqefj7GVzz@#^mnyt'
  segmentWriteKey:
  numAllowedActiveGames: 3
  softMinBuild: '0' # TODO: Make sure app can handle string
  hardMinBuild: '0'
